### PR TITLE
Offer to force kill if process couldn't be killed normally

### LINKED ISSUE #11: Forcefull termination
I just tried out fkill and the first process I tried to kill resulted in an error...   :smiley_cat:   In this particular case, I was trying to kill a process that apparently needed to be "terminated forcefully" (see the output below).  Maybe in these cases, fkill presents a secondary challenge to the terminal like "Are you sure you want to kill this process?" and then forcefully terminate upon yes, or cancel upon no.  Or maybe you don't want to allow the ability to forcefully terminate, in which a friendlier error message would probably suffice.

Just wanted to highlight the issue!

P.S.  for what its worth, I'm on Windows 7, currently using a git-bash flavored shell, node 6.2.1.

```bash
$ fkill
? Running processes: cnt
? Running processes: cntlm.exe 2200

AggregateError:
    Error: Killing process 2200 failed: ERROR: The process with PID 2200 could not be terminated.
    Reason: This process can only be terminated forcefully (with /F option).
        at Promise.all.then (C:/Users/********/AppData/Roaming/nvm/v6.2.1/node_modules/fkill-cli/node_modules/fkill/index.js:41:10)
    at AggregateError (C:\Users\********\AppData\Roaming\nvm\v6.2.1\node_modules\fkill-cli\node_modules\aggregate-error\index.js:19:3)
    at Promise.all.then (C:\Users\********\AppData\Roaming\nvm\v6.2.1\node_modules\fkill-cli\node_modules\fkill\index.js:41:10)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### PR DESCRIPTION
**Pull request by coffeedoughnuts**
Fixes #11

### CODE REVIEW

File: cli.js [hunk 1]
```diff
@@ -73,8 +73,20 @@ function filterProcesses(input, processes, flags) {
 		});
 }
 
+function handleFkillError(proc) {
+	inquirer.prompt([{
```
Comment (sindresorhus) [inline cli.js]: You need to return this so the chain is not broken.

File: cli.js [hunk 2]
```diff
@@ -73,8 +73,20 @@ function filterProcesses(input, processes, flags) {
...
+			return fkill(proc, {force: true});
+		}
+	});
+}
+
 if (cli.input.length === 0) {
 	init(cli.flags);
 } else {
-	fkill(cli.input, cli.flags);
+	fkill(cli.input, cli.flags).catch(() => handleFkillError(cli.input));
```
Comment (sindresorhus) [inline cli.js]: The prompt should only show when the terminal is interactive (`process.stdout.isTTY`), otherwise it should just print what processes it couldn't kill and recommend the `--force` flag.

File: cli.js [hunk 3]
```diff
@@ -73,8 +73,20 @@ function filterProcesses(input, processes, flags) {
 		});
 }
 
+function handleFkillError(proc) {
```
Comment (SamVerschueren) [inline cli.js]: I would rename this to `processes` instead of `proc`.

File: cli.js [hunk 4]
```diff
@@ -73,16 +73,20 @@ function filterProcesses(input, processes, flags) {
...
-		name: 'forceKill',
-		message: 'Error killing process. Would you like to use the force?'
-	}]).then(answer => {
-		if (answer.forceKill === true) {
-			return fkill(proc, {force: true});
-		}
-	});
+function handleFkillError(processes) {
+	if (process.stdout.isTTY === false) {
+		console.log(`Error killing process. Try \`fkill --force ${processes}\``);
```
Comment (sindresorhus) [inline cli.js]: Super nitpick, but use `process` word if there are only one process, otherwise `processes`, in `Error killing process`.

File: cli.js [hunk 5]
```diff
@@ -73,8 +73,25 @@ function filterProcesses(input, processes, flags) {
...
 
+function handleFkillError(processes) {
+	const suffix = processes.length > 1 ? 'es' : '';
+	if (process.stdout.isTTY === false) {
+		console.log(`Error killing process${suffix}. Try \`fkill --force ${processes.join(' ')}\``);
+	} else {
+		return inquirer.prompt([{
+			type: 'confirm',
+			name: 'forceKill',
+			message: `Error killing process${suffix}. Would you like to use the force?`
```
Comment (sindresorhus) [inline cli.js]: It doesn't make sense to have the suffix here. It's always only one process.

Comment (coffeedoughnuts) [inline cli.js]: You're right - though are we not contemplating adding 'kill all' functionality at a later stage (on other issues) - this would future proof the messaging no? Happy to remove it though. AFK for the rest of today though so will be a little later.

Comment (sindresorhus) [inline cli.js]: I don't like adding things just in case it's needed later. That just leads to lot of unused cruft in the codebase. We add things when we actually need it. I actually noticed this because it also returns the wrong value, `processes`.

**Comment by sindresorhus** [comment]
Awesome. This is nice UX :)
